server:
  port: 7001

spring:
  batch:
    job:
      enabled: false
  datasource:
    url: jdbc:postgresql://${db.batch.host:localhost}:${db.batch.port:5432}/batch?currentSchema=sbt
    driver-class-name: org.postgresql.Driver
    username: ${db.batch.username:batch}
    password: ${db.batch.password:batch}

logging:
 level:
  com.example: DEBUG 
